# Generated by Django 4.2.13 on 2025-01-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalCertificateCourseConfiguration',
            new_name='ExternalCertificateConfiguration',
        ),
    ]
