# Generated by Django 3.2.23 on 2024-06-26 15:14

from django.db import migrations, models

from openedx_certificates.compat import get_course_name


def fill_course_names(apps, _schema_editor):
    """Fill the course_name field for all existing certificates."""
    for certificate in apps.get_model("openedx_certificates", "ExternalCertificate").objects.all():
        course_name = get_course_name(certificate.course_id)
        certificate.course_name = course_name
        certificate.save()

class Migration(migrations.Migration):

    dependencies = [
        ('openedx_certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcertificate',
            name='invalidation_reason',
            field=models.TextField(blank=True, help_text='Reason for invalidating the certificate. If set, the certificate is invalidated.'),
        ),
        migrations.AddField(
            model_name='externalcertificate',
            name='course_name',
            field=models.CharField(help_text='Course name for which the certificate was issued', max_length=255),
        ),
        migrations.RunPython(fill_course_names, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='externalcertificate',
            unique_together=set(),
        ),
    ]
