# Generated by Django 4.2.18 on 2025-02-24 18:55

from django.db import migrations
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_certificates', '0002_invalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcertificatecourseconfiguration',
            name='course_id',
            field=opaque_keys.edx.django.models.LearningContextKeyField(
                help_text='The ID of the course or learning path.', max_length=255
            ),
        ),
        migrations.RenameField(
            model_name='externalcertificatecourseconfiguration',
            old_name='course_id',
            new_name='learning_context_key',
        ),
        migrations.AlterUniqueTogether(
            name='externalcertificatecourseconfiguration',
            unique_together={('learning_context_key', 'certificate_type')},
        ),
        migrations.AlterField(
            model_name='externalcertificate',
            name='course_id',
            field=opaque_keys.edx.django.models.LearningContextKeyField(
                help_text='ID of the course or learning path for which the certificate was issued', max_length=255
            ),
        ),
        migrations.RenameField(
            model_name='externalcertificate',
            old_name='course_id',
            new_name='learning_context_key',
        ),
    ]
