# Generated by Django 4.2.13 on 2025-01-22 15:43

from django.db import migrations, models


def populate_resource_id(apps, schema_editor):
    """
    Populate the resource_id field with the value from course_id for all existing rows.
    """
    ExternalCertificateConfiguration = apps.get_model('openedx_certificates', 'ExternalCertificateConfiguration')
    for certconfig in ExternalCertificateConfiguration.objects.all():
        certconfig.resource_id = certconfig.course_id
        certconfig.save()


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_certificates', '0002_rename_externalcertificatecourseconfiguration_externalcertificateconfiguration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalcertificateconfiguration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='externalcertificateconfiguration',
            name='resource_id',
            field=models.CharField(blank=True, help_text='The ID of the resource (e.g., course_id, learner_path_uuid).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externalcertificateconfiguration',
            name='resource_type',
            field=models.CharField(choices=[('course', 'Course'), ('learning_path', 'Learning Path')], default='course', help_text='The type of the resource.', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='externalcertificateconfiguration',
            unique_together={('resource_id', 'certificate_type')},
        ),
        migrations.RunPython(populate_resource_id),
        migrations.RemoveField(
            model_name='externalcertificateconfiguration',
            name='course_id',
        ),
        migrations.AlterField(
            model_name='externalcertificateconfiguration',
            name='resource_id',
            field=models.CharField(max_length=255, help_text='The ID of the resource (e.g., course, learning path).'),
        ),
    ]
