# Generated by Django 4.2.13 on 2025-01-22 16:00

from django.db import migrations, models


def populate_resource_id(apps, schema_editor):
    """
    Populate the resource_id field with the value from course_id for all existing rows.
    """
    ExternalCertificate = apps.get_model('openedx_certificates', 'ExternalCertificate')
    ExternalCertificate.objects.update(resource_id=models.F('course_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_certificates', '0003_alter_externalcertificateconfiguration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalcertificate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='externalcertificate',
            name='resource_id',
            field=models.CharField(blank=True, help_text='ID of the resource (e.g., course, learning path)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externalcertificate',
            name='resource_type',
            field=models.CharField(choices=[('course', 'Course'), ('learning_path', 'Learning Path')], default='course', help_text='Type of the resource for which the certificate was issued', max_length=50),
        ),
        migrations.AlterField(
            model_name='externalcertificateconfiguration',
            name='resource_id',
            field=models.CharField(blank=True, help_text='The ID of the resource (e.g., course_id, learner_path_uuid).', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='externalcertificate',
            unique_together={('user_id', 'resource_id', 'resource_type', 'certificate_type')},
        ),
        migrations.RunPython(populate_resource_id),
        migrations.AlterField(
            model_name='externalcertificate',
            name='resource_id',
            field=models.CharField(max_length=255, help_text='ID of the resource (e.g., course, learning path)', null=False, blank=False),
        ),
        migrations.RemoveField(
            model_name='externalcertificate',
            name='course_id',
        ),
    ]
